---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: get testing service host ips
      command: python loadtest/inventory/ec2.py
      args:
        chdir: "{{ lookup('env', 'WORKSPACE') }}"
      register: service_host_ips

    - name: set hostname to viarables
      - set_fact:
          host_ips: "{{ service_host_ips.stdout }}"

- hosts: tag_Env_{{ app_env }}:&tag_Cluster_{{ app_cluster }}:&tag_Role_{{ qa_box }}
  serial: "100%"
  gather_facts: no
  tasks:
    - name: Get Ip address
      shell: echo {{ host_ips }}
